Repository Homeat/Server, pull requests merged in 2024-07, with the labels that each got.

#157 Refactor/homeat 73
  src/main/java/homeat/backend/domain/post/controller/FoodTalkController.java
  src/main/java/homeat/backend/domain/post/controller/InfoTalkController.java
  src/main/java/homeat/backend/domain/post/dto/FoodRequestDTO.java
  src/main/java/homeat/backend/domain/post/dto/FoodResponseDTO.java
  src/main/java/homeat/backend/domain/post/dto/InfoRequestDTO.java
  src/main/java/homeat/backend/domain/post/entity/FoodRecipe.java
  src/main/java/homeat/backend/domain/post/entity/FoodTalk.java
  src/main/java/homeat/backend/domain/post/repository/PostLoveRepository.java
  src/main/java/homeat/backend/domain/post/service/FoodTalkService.java
  src/main/java/homeat/backend/domain/post/service/InfoTalkService.java
Labels: :recycle: refactor

#156 Feature/homeat 62 과거 지출 내역 추가 및 세부 지출 내역 조회
  src/main/java/homeat/backend/domain/analyze/repository/FinanceDataRepository.java
  src/main/java/homeat/backend/domain/home/controller/HomeController.java
  src/main/java/homeat/backend/domain/home/dto/HomeRequestDTO.java
  src/main/java/homeat/backend/domain/home/dto/HomeResponseDTO.java
  src/main/java/homeat/backend/domain/home/entity/DailyExpense.java
  src/main/java/homeat/backend/domain/home/repository/DailyExpenseRepo.java
  src/main/java/homeat/backend/domain/home/repository/ReceiptRepo.java
  src/main/java/homeat/backend/domain/home/repository/querydsl/DailyExpenseRepoCST.java
  src/main/java/homeat/backend/domain/home/repository/querydsl/DailyExpenseRepoImpl.java
  src/main/java/homeat/backend/domain/home/service/HomeService.java
Labels: :sparkles: feature

#160 Refactor/homeat-77 리프레시 토큰 전달 방식 변경
  .gitignore
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/controller/MemberErrorStatus.java
  src/main/java/homeat/backend/domain/user/dto/MemberResponse.java
  src/main/java/homeat/backend/domain/user/repository/MemberRepository.java
  src/main/java/homeat/backend/domain/user/service/MemberMapper.java
  src/main/java/homeat/backend/domain/user/service/MemberService.java
  src/main/java/homeat/backend/global/security/LoginFilter.java
  src/main/java/homeat/backend/global/security/LoginService.java
  src/main/java/homeat/backend/global/security/LogoutFilter.java
Labels: :recycle: refactor

#163 Bug/homeat 83
  src/main/java/homeat/backend/domain/post/controller/FoodTalkController.java
  src/main/java/homeat/backend/domain/post/controller/InfoTalkController.java
  src/main/java/homeat/backend/domain/post/dto/FoodRequestDTO.java
  src/main/java/homeat/backend/domain/post/dto/FoodResponseDTO.java
  src/main/java/homeat/backend/domain/post/dto/InfoRequestDTO.java
  src/main/java/homeat/backend/domain/post/dto/InfoResponseDTO.java
  src/main/java/homeat/backend/domain/post/service/FoodTalkService.java
  src/main/java/homeat/backend/domain/post/service/InfoTalkService.java
  src/main/java/homeat/backend/global/exception/ExceptionAdvice.java
Labels: :bug: bug, :recycle: refactor

#169 Bug/homeat 98 비활성 사용자 처리 수정
  src/main/java/homeat/backend/domain/mypage/controller/MyPageController.java
  src/main/java/homeat/backend/domain/mypage/service/MyPageService.java
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/controller/MemberErrorStatus.java
  src/main/java/homeat/backend/domain/user/dto/CustomUserDetails.java
  src/main/java/homeat/backend/domain/user/service/MemberService.java
  src/main/java/homeat/backend/global/security/LoginFilter.java
Labels: :bug: bug

#170 Bug/homeat 99 회원정보 수정 처리 오류
  src/main/java/homeat/backend/domain/mypage/controller/MyPageController.java
  src/main/java/homeat/backend/domain/mypage/dto/MyPageRequest.java
  src/main/java/homeat/backend/domain/mypage/service/MyPageService.java
Labels: :bug: bug

#172 Bug/homeat 102
  src/main/java/homeat/backend/domain/home/repository/querydsl/DailyExpenseRepoCST.java
  src/main/java/homeat/backend/domain/home/repository/querydsl/DailyExpenseRepoImpl.java
  src/main/java/homeat/backend/domain/home/service/HomeService.java
Labels: :bug: bug, :recycle: refactor

#175 Fix/HOMEAT-103
  src/main/java/homeat/backend/domain/mypage/service/MyPageMapper.java
  src/main/java/homeat/backend/domain/mypage/service/MyPageService.java
Labels: :bug: bug
