Repository Homeat/Server, pull requests merged in 2024-02, with the labels that each got.

#50 Feature/38
  src/main/java/homeat/backend/domain/post/controller/InfoTalkController.java
  src/main/java/homeat/backend/domain/post/dto/InfoHashTagDTO.java
  src/main/java/homeat/backend/domain/post/dto/queryDto/InfoTalkSearchCondition.java
  src/main/java/homeat/backend/domain/post/entity/InfoHashTag.java
  src/main/java/homeat/backend/domain/post/entity/InfoTalk.java
  src/main/java/homeat/backend/domain/post/repository/querydsl/InfoTalkRepositoryCustom.java
  src/main/java/homeat/backend/domain/post/repository/querydsl/InfoTalkRepositoryImpl.java
  src/main/java/homeat/backend/domain/post/service/InfoTalkService.java
Labels: :sparkles: feature

#51 Feature/46 Refactor: 토큰 예외 응답 처리
  src/main/java/homeat/backend/domain/health/controller/HealthController.java
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/controller/MemberConverter.java
  src/main/java/homeat/backend/domain/user/dto/MemberInfoRequest.java
  src/main/java/homeat/backend/domain/user/dto/MemberInfoResponse.java
  src/main/java/homeat/backend/domain/user/dto/MemberResponse.java
  src/main/java/homeat/backend/domain/user/repository/MemberRepository.java
  src/main/java/homeat/backend/domain/user/service/MemberCommandService.java
  src/main/java/homeat/backend/global/config/SecurityConfig.java
  src/main/java/homeat/backend/global/exception/ExceptionAdvice.java
  src/main/java/homeat/backend/global/security/jwt/JwtEntryPoint.java
  src/main/java/homeat/backend/global/security/jwt/JwtErrorStatus.java
  src/main/java/homeat/backend/global/security/jwt/JwtFilter.java
  src/main/java/homeat/backend/global/security/jwt/JwtUtil.java
  src/main/java/homeat/backend/web/controller/RootController.java
Labels: :recycle: refactor

#60 Feature/38
  src/main/java/homeat/backend/BackendApplication.java
  src/main/java/homeat/backend/domain/post/controller/FoodTalkController.java
  src/main/java/homeat/backend/domain/post/controller/InfoTalkController.java
  src/main/java/homeat/backend/domain/post/dto/queryDto/FoodTalkSearchCondition.java
  src/main/java/homeat/backend/domain/post/entity/FoodRecipe.java
  src/main/java/homeat/backend/domain/post/entity/FoodTalk.java
  src/main/java/homeat/backend/domain/post/repository/querydsl/FoodTalkRepositoryImpl.java
  src/main/java/homeat/backend/domain/post/service/FoodTalkService.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#68 Feature/38
  src/main/java/homeat/backend/domain/post/controller/InfoTalkController.java
  src/main/java/homeat/backend/domain/post/dto/queryDto/FoodTalkTotalView.java
  src/main/java/homeat/backend/domain/post/dto/queryDto/InfoTalkTotalView.java
  src/main/java/homeat/backend/domain/post/repository/querydsl/FoodTalkRepositoryImpl.java
  src/main/java/homeat/backend/domain/post/repository/querydsl/InfoTalkRepositoryImpl.java
  src/main/java/homeat/backend/domain/post/service/InfoTalkService.java
Labels: :recycle: refactor

#71 Feature/69 Feat: 회원 상태 변경 등 누락 api 추가
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/entity/Member.java
  src/main/java/homeat/backend/domain/user/service/MemberCommandService.java
Labels: :sparkles: feature

#73 docs : Mutipart 파일 용량 제한 128MB로 변경
  src/main/resources/application.yml
Labels: :memo: docs

#74 Feature/69 Refactor: 회원가입시 토큰 반환
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/controller/MemberConverter.java
  src/main/java/homeat/backend/domain/user/dto/MemberResponse.java
  src/main/java/homeat/backend/domain/user/service/MemberCommandService.java
Labels: :recycle: refactor

#83 Feature/72 Faet: 현재 위치 동네, 주변 동네 탐색
  build.gradle
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/dto/AddressResponse.java
  src/main/java/homeat/backend/domain/user/dto/MemberResponse.java
  src/main/java/homeat/backend/domain/user/entity/Address.java
  src/main/java/homeat/backend/domain/user/repository/AddressRepository.java
  src/main/java/homeat/backend/domain/user/service/AddressService.java
Labels: :sparkles: feature

#93 Feature/72 Feat: 키워드로 주변 동네 검색 구현
  src/main/java/homeat/backend/domain/address/controller/AddressController.java
  src/main/java/homeat/backend/domain/address/dto/AddressResponse.java
  src/main/java/homeat/backend/domain/address/entity/Address.java
  src/main/java/homeat/backend/domain/address/repository/AddressRepository.java
  src/main/java/homeat/backend/domain/address/service/AddressService.java
  src/main/java/homeat/backend/domain/user/controller/MemberController.java
  src/main/java/homeat/backend/domain/user/controller/MemberConverter.java
  src/main/java/homeat/backend/domain/user/dto/MemberResponse.java
Labels: :sparkles: feature, :recycle: refactor

#96 chore : 정보토크 Member EAGER로 변경
  build.gradle
  src/main/java/homeat/backend/BackendApplication.java
  src/main/java/homeat/backend/domain/post/entity/InfoPicture.java
  src/main/java/homeat/backend/domain/post/entity/InfoTalk.java
Labels: :recycle: refactor
